language: python
python:
  - "3.5"
  - "3.6"
services:
  - postgresql
before_install:
  - export TZ=Europe/Moscow
  - nvm install 8.0
  - nvm use 8.0
install:
  - mkdir -p logs
  - pip install -r requirements_dev.txt
  - npm install
  - "npm run grunt build:development"
before_script:
  - psql -c "CREATE USER airy WITH password 'airy' CREATEDB;" -U postgres
script:
  - flake8 --max-complexity=8 fabfile
  - flake8 --max-complexity=10 airy
  - flake8 --max-complexity=8 alembic/env.py
  - safety check --bare
  - bandit -r -x tests,settings airy
  - py.test airy/tests
  - "npm run grunt check:js check:css check:html"
