language: python
python:
  - "3.4"
  - "3.5"
services:
  - postgresql
before_install:
  - nvm install 5.0
  - nvm use 5.0
install:
  - mkdir -p logs
  - cp airy/settings.py.example airy/settings.py
  - pip install -r requirements-dev.txt
  - npm install
  - npm run-script bower install
  - "npm run-script grunt build:development"
before_script:
  - psql -c "CREATE USER airy WITH password 'airy' CREATEDB;" -U postgres
script:
  - flake8 --max-complexity=8 fabfile
  - flake8 --max-complexity=10 airy
  - flake8 --max-complexity=8 alembic/env.py
  - py.test airy/tests
  - "npm run-script grunt check:js check:css check:html"
